### ISSUE TITLE
Import HIBP Class from Crossfeed Repo

### ISSUE THREAD

**Issue by stewartl97** [cisagov/pe-reports#102]
# 💡 Summary #

Create scripts to pull HIBP data into P&E database.  Currently housed in Crossfeed Repo.

## Implementation notes ##
- Create class for HIBP data pulls.
- Return dataframes

## Acceptance criteria ##

How do we know when this work is done?

- [ ]  run `pip install -e .`
- [ ] run `pre-commit run --all-files`
- [ ] run `pytest /tests`
- [ ] run `pe-reports $(date "+%Y-%m-%d") data/ output/ --db-creds-file=/creds`
- [ ] All code meets dev-standards

**Comment by stewartl97** [comment]
@DJensen94 @aloftus23 do we have a status on this?  remember the goal is not for a successful PR, but to have the code contained within our project.

**Comment by aloftus23** [comment]
@stewartl97  At the end of last week, I was working on this issue which I wrapped together with issues #101, #110, #107. Was busy with reports yesterday so now I'm working on getting the pre-commits passed so I can draft PR what I have so far.

**Comment by stewartl97** [comment]
We will need to rewrite this class in python before incorporating it into our repo.  Closing this issue as wontfix.
