### ISSUE TITLE
Import CyberSixGill Classes from Crossfeed Repo

### ISSUE THREAD

**Issue by stewartl97** [cisagov/pe-reports#103]
# 💡 Summary #

Create scripts to pull CyberSixGill data into P&E database.  Currently housed in Crossfeed Repo.

## Implementation notes ##
- Create class for CyberSixGill data pulls.
- Return dataframes

## Acceptance criteria ##

How do we know when this work is done?

- [ ]  run `pip install -e .`
- [ ] run `pre-commit run --all-files`
- [ ] run `pytest /tests`
- [ ] run `pe-reports $(date "+%Y-%m-%d") data/ output/ --db-creds-file=/creds`
- [ ] All code meets dev-standards

**Comment by DJensen94** [comment]
Implemented in PR #117. Currently in Draft mode, waiting for UI PR to pass before submitting for approval
