### ISSUE TITLE
Introduce Classes into pages.py

### ISSUE THREAD

**Issue by DJensen94** [cisagov/pe-reports#104]
Classes have been created for each datasource, now implement those classes into pages.py, removing unnecessary passing of variables

**Comment by DJensen94** [comment]
Classes aree implemented into pages.py, depending on dev team requests we may need to break this into several PRs for each page

**Comment by stewartl97** [comment]
@DJensen94 Has this been successfully merged into a PR yet?

**Comment by DJensen94** [comment]
Submitted PR for review: https://github.com/cisagov/pe-reports/pull/114

**Comment by stewartl97** [comment]
Moving to Sprint 9 to consolidate PR's for easier tracking.

**Comment by DJensen94** [comment]
This Issue was completed and merged through the following PR: https://github.com/cisagov/pe-reports/pull/114
