### ISSUE TITLE
Identify Way to Backup Postgres Database For Easy Loading Onto Each Developer Computer

### ISSUE THREAD

**Issue by stewartl97** [cisagov/pe-reports#113]
# 💡 Summary #

Need to dump Postgres database and all objects in such a way as to make the restore easy to complete on a developer computer.

## Motivation and context ##

Currently database backups do not support significant schema changes such as new roles or users.

## Implementation notes ##

- Database should be restorable without errors

## Acceptance criteria ##

How do we know when this work is done?

- [ ] A developer can run a quick command and the database will be able to load with no errrors.
- [ ] Database backups will be performed after each report generation to capture latest data sets and changes.

**Comment by cduhn17** [comment]
I have not tried this but looks like it may be an option to facilitate this request to get a dump sql with schema and data[#seethis link](https://pypi.org/project/dump/).

**Comment by stewartl97** [comment]
Moving into Sprint 9 as part of the technical debt.
