### ISSUE TITLE
Add user login and API endpoint authentication 

### ISSUE THREAD

**Issue by cduhn17** [cisagov/pe-reports#116]
# 💡 Summary #

Implement user login, complete with self server password administration to establish API key for REST endpoint authentication.

## Motivation and context ##

The REST endpoints are needed to share PE Reports data to 3rd party as well as inter agency partners. The api key and associated login management are needed to safely control endpoint usage. 

## Implementation notes ##

The user that has a need to consume PE Reports data, would register with the REST system. The user would create a username and password that would create an API key that would then be used to make API calls and return data to the user programmatically. The REST endpoint will work in conjunction with our current Flask application #115.
-Remaining tasks
- [x] Create api token.(This task is similar to creating the reset token)
- [x] Create separated database configuration/connection for FastAPI
- [ ] Create dependent functions to pull API user functions.
- [x] Create REST api endpoint and apply authorization technique utilizing api token
- [x] Create a user page to display the user api key

## Acceptance criteria ##

How do we know when this work is done?

- [ ] All testing checks will pass.
- [ ]  All P&E source code in COOL (Crossfeed and PE Reports) will exist in our P&E repo
- [ ]  Code in P&E repo will be treated as authoritative
- [ ]  Team source code collaboration will be done through P&E repo rather than via Teams
- [x] User will be able to create a new account.
- [ ] Self administer password resets.
- [ ] Receive API key to interact with PE Reports data.

**Comment by stewartl97** [comment]
@cduhn17 Is this ready to be handed off to the team for completion?  If so can you check off what has been completed in acceptance criteria, and add any missing pieces?

**Comment by cduhn17** [comment]
The initial method to establish REST endpoints was to use the flask REST framework. The current effort is using FasteAPI to implement and authorize endpoints and will be used to supply data internally to the flask app.

**Comment by cduhn17** [comment]
This issue becomes part of issue #337
