### ISSUE TITLE
Create module to redact/remove PII

### ISSUE THREAD

**Issue by DJensen94** [cisagov/pe-reports#118]
This module should accept a dataframe and then remove any values that can be identified as PII. Including,
Names,
Emails,
SSN,
Credit Card Numbers,
Phone numbers,
birth dates,
etc.

**Comment by DJensen94** [comment]
Everything seems to be working for redaction purposes, I need to test on real data though, so I am going to plug it into part of the report generator to see how it works on data coming out of the db before I plug it into scans going into the db

**Comment by DJensen94** [comment]
After that test I will create the PR for dev team to validate

**Comment by stewartl97** [comment]
@DJensen94 what input does the script currently take?  could you put together a custom CSV with a PII field name and different data formats in there (SSN, phone, DOB, etc) and see what it catches.
