### ISSUE TITLE
VS team scanning script integration

### ISSUE THREAD

**Issue by cduhn17** [cisagov/pe-reports#123]
# 💡 Summary #

VS team script integration into regular PE-report scripts

## Motivation and context ##

Currently the script is executed by the VS team on their local machine for reporting purposes and the idea is to automate this process. The result of automation is a reduction in labor for an operator to execute the script, increase the value of our data set and consistent script execution.

## Implementation notes ##

- The current docker has the script that will be harvested and put in the COOL.  
- Build out a schema to house the data that is collected when running the script. 
- The output file to be delivered(emailed??)

## Acceptance criteria ##

How do we know when this work is done?

- [x] Get script from docker
- [x] Make any necessary changes to the script to fit our standard
- [x] Create a new database schema to store the data that is gathered when script is executed.
- [x] Validate data gathered data
- [x] Insert data into PE database

**Comment by DJensen94** [comment]
The VS team seemed very much against us taking over control of the pshtt and other scripts, they recommended we branch their code and make any adjustments that we would need to run independently.

**Comment by DJensen94** [comment]
I have updated their pshtt script in our branch to work with the newest version of sslyze, and built out a new pshtt_results table in the database. I have also developed a wrapper script that multithreads through our subdomains and runs pshtt on each and saves them to our database.
