### ISSUE TITLE
Setup Reports for Weekly Run

### ISSUE THREAD

**Issue by stewartl97** [cisagov/pe-reports#127]
# 💡 Summary #

Set up Crossfeed and Scripts to run PE report weekly.  This needs to move to as close to zero interaction as possible by 3/31.

## Motivation and context ##

To meet the directive to begin weekly delivery by Q3

## Implementation notes ##

Please note below any requirements or additional work that needs to be completed to meet this objective.

- an example for how this would be used
- what this would look like
- how this would act
- any related work, including links to related issues

## Acceptance criteria ##

How do we know when this work is done?

- [ ] Reports will be generated every Thursday and left in a folder for QC.
- [ ] Once a reviewer spot checks, script can be run to transmit the data.

**Comment by DJensen94** [comment]
The code is ready for weekly runs and delivery. (However management has told us we are staying on a biweekly delivery schedule)
