### ISSUE TITLE
Add New Team Member: cduhn17

### ISSUE THREAD

**Issue by schmelz21** [cisagov/pe-reports#13]
# 💡 Summary #

Craig Dunn is a new member to the P&E Team and will be an owner of https://github.com/cisagov/pe-reports

## Motivation and context ##

Craig Dunn's GitHub profile = cduhn17

## Implementation notes ##

- Coordinate with Fusion Dev to add Craig's GitHub profile to 'cisagov' organization.
- Add Craig's GitHub profile as owner to cisa/pe-reports
- update https://github.com/cisagov/pe-reports/blob/develop/.github/CODEOWNERS 
```
# These owners will be the default owners for everything in the
# repo. Unless a later match takes precedence, these owners will be
# requested for review when someone opens a pull request.
* @aloftus23 @cduhn17 @dav3r @DJensen94 @elr64 @felddy @jsf9k @mcdonnnj @schmelz-ctr @stewartl97

```
## Acceptance criteria ##

How do we know when this work is done?

- [x] Craig is successfully added to https://github.com/cisagov/pe-reports
- [x] CODEOWNERS is updated.

**Comment by jsf9k** [comment]
I invited @cduhn17 to the cisagov organization on July 16, but the invitation has not yet been accepted.

**Comment by schmelz21** [comment]
Sounds good - I will let him know.

**Comment by schmelz21** [comment]
@stewartl97 I see your PR https://github.com/cisagov/pe-reports/pull/25 was approved and merged. Marking this issue complete.
