### ISSUE TITLE
Upgrade python minimum version

### ISSUE THREAD

**Issue by cduhn17** [cisagov/pe-reports#133]
# 💡 Summary #

Update setup.py to require a minimum Python version to run PE-Reports

## Motivation and context ##

As new python versions emerge over time the packages that are required by PE-Reports are upgraded to work with newer versions of python rendering older versions of some packages incompatible. 

## Implementation notes ##

Determine optimal python version to use
Determine if the current package versions are compatible with the python version
Determine a time frame and upgrading process for python versions and compatible package versions.
*Note: We can hard code python version and package version to ensure expected operation. The con of doing this is that over time our application may become susceptible to security vulnerabilities. 

## Acceptance criteria ##

How do we know when this work is done?

- [ ] setup.py updated with desired python version.
- [ ] requirements.txt updated with package version appropriate for python version.

**Comment by stewartl97** [comment]
Team has settled on Python 3.10.0 as our minimal version.
