### ISSUE TITLE
Replace python-pptx graphs with Matplotlib graphing libraries

### ISSUE THREAD

**Issue by schmelz21** [cisagov/pe-reports#14]
# 💡 Summary #

Due to graphing errors with python-pptx and pdf conversions on mac OS, all graphing functions will be replace with the [Matplotlib](https://matplotlib.org/) package.

## Motivation and context ##
Primarily this improvement allows for better quality control and addresses the open issues presented in https://github.com/cisagov/pe-reports/issues/9- "Define constants for graph sizing and positioning".

## Implementation notes ##

Please provide details for implementation, such as:

- From the local P&E Teams repository take scripts from charts.py and update GitHub [stylesheets.py](src/pe_reports/stylesheet.py)
- Adjust references in [pages.py](src/pe_reports/pages.py) 
- Update setup.py with Matplotlib instillation requirements

## Acceptance criteria ##

How do we know when this work is done?

- [x]  Report runs end-to-end from command-line.
- [x] Must pass Issue requirements - https://github.com/cisagov/pe-reports/issues/18
- [x] Must pass Issue requirements - https://github.com/cisagov/pe-reports/issues/21
- [x] Code meets CISA dev-standards and tests.

**Comment by cduhn17** [comment]
This issue has been addressed and merged into develop branch.
