### ISSUE TITLE
Error Handling for PDF output over 20MB

### ISSUE THREAD

**Issue by schmelz21** [cisagov/pe-reports#15]
# 🐛 Summary #

Some clients can't receive files over 20 MB and bounce back when emailed. We should add some functionality in our scripts to either flag on pdfs that are over 20MB, or automatically zip the files once the csv attaching and encrypting process has been complete.

## To reproduce ##

1. Run production and evaluate attachment file sizes. This is a rare occurrence, but can happen.

## Expected behavior ##

In the pe-report scripts, flag any reports that are greater than or equal to 20MB.

Alternatively remove the "content" of the web mentions (the post/comment text) because it creates the large file sizes. The 'content' of the dark web mentions can still be included as the data is limited. Other attributes of the web mentions should not be removed (E.g. title and url)

Possible solutions:
- Get rid of web mentions raw data and keep dark web.
- Truncate the list.
- Don't embed raw data.
- Re-evaluate pe_reports code.
- Flag files sizes over 20MB 

## Any helpful log output or screenshots ##
![Screen Shot 2021-07-09 at 11 24 23 AM](https://user-images.githubusercontent.com/81192860/126213514-daf59800-d8a3-4d2d-8635-44dd9dd3052b.png)

**Comment by stewartl97** [comment]
Another alternative to consider might be to split the email.  So send the .pdf if it is under 20MB and if the compressed supporting docs are under 20MB then send those.

**Comment by cduhn17** [comment]
This has been addressed and implemented in the code, the result of this change is, that when the file size 4GB(updated file size threshold) is exceeded there is an error thrown and the report is flagged.
