### ISSUE TITLE
Create view connecting cyhy db data and current PE orgs

### ISSUE THREAD

**Issue by aloftus23** [cisagov/pe-reports#165]
# 💡 Summary #

This view can show all the contact information stored for the current P&E orgs. 

*Can look into adding more relevant cyhydb data

- [X] PE database table has been created that holds all CyHy org tech/distro contact info
- [X] View has been created that neatly displays the contact info for only PE orgs (vw_orgs_contact_info)

**Comment by stewartl97** [comment]
@arng4108 assigned to you for review as you have been creating the views.

**Comment by arng4108** [comment]
@stewartl97 
The cyhy_contacts table  in the PE staging DB looks good to me. 

I also created a view that presents the contact info a bit more neatly, includes organizations_uid, and only includes PE organizations (as opposed to all cyhy db orgs). 

Besides that, everything looks good. Although, I'm not sure what else to add in terms of "additional relevant cyhy data"

**Comment by arng4108** [comment]
I could add the "security_contact_emails" from the dotgov_domains table to the view, but the general consensus from the team seems to be that I shouldn't add it.

**Comment by arng4108** [comment]
cyhy_contacts table is accounted for in the database. Additionally, "vw_orgs_contact_info" view has been created in the staging database that presents the contact info for all orgs.
