### ISSUE TITLE
Add P&E Mailer Automation - Module

### ISSUE THREAD

**Issue by schmelz21** [cisagov/pe-reports#17]
# 💡 Summary #

To further automate the delivery of P&E Reports to customers, a module/program will be implemented to retrieve pe_report output and deliver to the appropriate customer's email. Ideally this would be an in-line process that can be turned on/off will running the pe_reports module.

## Motivation and context ##

This would fully automate the P&E Reports delivery process. Secondarily allows for scalability and acquiring more customers at a faster pace. With proper test, it improves quality control.

## Implementation notes ##

- Proposed Architecture

```
├── src
│   ├── pe_reports
│   │   ├── __init__.py
│   │   ├── __main__.py
│   │   ├── _version.py
│   │   ├── data
│   │   ├── file_1.py
│   │   ├── file_2.py
│   │   └── report_generator.py
│   ├── pe_mailer
│   │   ├── __init__.py
│   │   ├── __main__.py
│   │   ├── _version.py
│   │   ├── data
│   │   ├── file_1.py
│   │   ├── file_2.py
│   │   └── mailer.py
└── tests
    ├── conftest.py
    └── test_pe_reports.py
    └── test_pe_mailer.py
├── setup.py
├── docker-compose/yml????
```
- Elegantly include secondary command line process for [mailer Usage](https://github.com/cisagov/cyhy-mailer).
- Update setup.py  to handle multiple `entry_points={'console_scripts':[ ]`
- Update dependancies for a python `import pe_mailer`

## Acceptance criteria ##

How do we know when this work is done?

- [x] TBD

**Comment by schmelz21** [comment]
@elr64 I updated the summery to start a conversation on how best to implement the mailer piece into pe-reports. Have a look. Couple of unknowns on my part is the docker dependency - is it critical?  And what I added may not nesacerily be compliant to dev-standards just yet. I figure we hash out dependancies first. Circling in @cduhn17 and @stewartl97 too.

**Comment by stewartl97** [comment]
@elr64 how close are we to having a module we can plug into our report tool?

**Comment by schmelz21** [comment]
@elr64,
@cduhn17 and I are planning to review your code submitted next week to evaluate implementation. May be sending out a time to meet to go over the scripts. Moving to[ In Progress](https://github.com/cisagov/pe-reports/projects/3#column-15579253) .

**Comment by schmelz21** [comment]
Update: @stewartl97 , @cduhn17  - current scripts provided by @elr64  are working locally. Updating code to conform to pe-reports' architecture so to create a pull-request for source control.
