### ISSUE TITLE
Update line charts to have abbreviated months on the axis instead of numeric dates

### ISSUE THREAD

**Issue by DJensen94** [cisagov/pe-reports#175]
# 💡 Summary #

Update the time chart axis to have abbreviated months instead of numeric months

## Motivation and context ##
This is to improve readability

## Implementation notes ##

Update the chart function to change the date format

## Acceptance criteria ##

How do we know when this work is done?

- [X] Both line charts have month abbreviations
- [ ] Pass pre-commits and tests to merge with staging

**Comment by aloftus23** [comment]
Completed
