### ISSUE TITLE
Add live_domain column to subdomain table

### ISSUE THREAD

**Issue by DJensen94** [cisagov/pe-reports#183]
# 💡 Summary #
To better track, scan and report on subdomains we need to monitor which subdomains are live. We will add a new column that will say whether a subdomain is accessible from the internet, if it is not and we cannot get any info from it we will mark it as false so we don't waist time scanning it on our various scans.
## Implementation notes ##
We will need to add a new boolean column called "is_live" to the subdomains table
We then will add a new scan or add to the subdomain scan to verify if a scan is live or not

## Acceptance criteria ##

How do we know when this work is done?

- [ ] new "is_live" column is added to the subdomain table
- [ ] values is updated in the subdomain scan

**Comment by stewartl97** [comment]
@DJensen94 what is the status of this issue?
