### ISSUE TITLE
Empty Charts Issue

### ISSUE THREAD

**Issue by stewartl97** [cisagov/pe-reports#188]
# 🐛 Summary #

Charts in the reports that have no data show negative numbers on the Y Axis.  It would be preferable to show all charts starting at 0 as we are only dealing with positive numbers in general.

## To reproduce ##

1. Review any report that has no data, and you will see the chart's Y axis in the negative.

## Expected behavior ##

Charts start at zero and count up.

```

**Comment by DJensen94** [comment]
Issue fixed in PR #192
