### ISSUE TITLE
Empty Tables Need Default Value

### ISSUE THREAD

**Issue by stewartl97** [cisagov/pe-reports#189]
# 🐛 Summary #

Currently tables show as empty space if there is no data to be displayed.  

## To reproduce ##

1. View a chart with no data.

## Expected behavior ##

Generate a friendly message noting that there are no findings for the time period.  ideally a merged field that is contextually appropriate (i.e. There has been no identifiable dark web activity for this period.)

- [X] Function has been implemented that adds a "no new data" note to empty tables
- [ ] Function needs to give table-specific message

**Comment by aloftus23** [comment]
Implemented with reportlab changes.
