### ISSUE TITLE
Improve use of schema to validate arguments

### ISSUE THREAD

**Issue by schmelz21** [cisagov/pe-reports#19]
# 💡 Summary #

Noted in ['bug-unusable-package'](https://github.com/cisagov/pe-reports/pull/6#discussion_r672830045), validate the arguments by using python package `schema`. `REPORT_DATE` and `DATA_DIRECTORY` should exist at a minimum.

## Motivation and context ##

Motivation is to improve quality of code.

## Implementation notes ##

Please provide details for implementation, such as:

- https://pypi.org/project/schema/

## Acceptance criteria ##

How do we know when this work is done?

- [x] schema.is_valid(data) will return True

**Comment by cduhn17** [comment]
Schema integration has been implemented and has been merged into develop branch(unsure of what PR#)
