### ISSUE TITLE
Create more pe-source pytests

### ISSUE THREAD

**Issue by aloftus23** [cisagov/pe-reports#198]
# 💡 Summary #

Only a small percentage of our code is covered by tests. Possible tests:
- db connections
- data cleanup
- pdf creation

## Motivation and context ##

Improve functionality and pass Coveralls checks.

## Acceptance criteria ##

- [ ] all new and existing pytests need to pass

**Comment by cduhn17** [comment]
@aloftus23 , 

Can this be combined with #202?

**Comment by aloftus23** [comment]
> @aloftus23 ,
> 
> Can this be combined with #202?

Main reason I split it up is because the pe-report tests rely on future PRs that haven't been merged yet. Such as #191 #195. There's a PR already linked to this issue (#201) that has a few tests specifically for the pe-source module.

Also, probably best to only focus on one module to avoid scope creep.
