### ISSUE TITLE
Define variable for empty iterations

### ISSUE THREAD

**Issue by schmelz21** [cisagov/pe-reports#21]
# 💡 Summary #

In reference to https://github.com/cisagov/pe-reports/pull/6#discussion_r672830853, all report objects need to be defined as a variable in the event an iteration renders empty. This primarily applies in the pptx object 'shape' from 'shapes' and will need to be adjusted accordingly when applying the matplotlib libraries. Issue -https://github.com/cisagov/pe-reports/issues/14

## Motivation and context ##

Considered a quality improvement to code.

## Implementation notes ##

Please provide details for implementation, such as:

- From [pptx-python](https://github.com/cisagov/pe-reports/pull/6) - the scope of 'shape':
```
- from pptx import Presentation

SLD_LAYOUT_TITLE_AND_CONTENT = 1

prs = Presentation()
slide_layout = prs.slide_layouts[SLD_LAYOUT_TITLE_AND_CONTENT]
slide = prs.slides.add_slide(slide_layout)
shapes = slide.shapes
```

- Example stylesheets.py: Declare a `shape` variable in the event `slide.shapes` is empty.
```
   @staticmethod
    def shapes(slide):
        """Create a text frame."""
        for shape in slide.shapes:
            if not shape.has_text_frame:
                continue
        return shape
```

## Acceptance criteria ##

How do we know when this work is done?

- [x] Return value `shape` on empty iteration

**Comment by cduhn17** [comment]
This has been merged into develop branch per PR#31
