### ISSUE TITLE
Flask UI Cybersixgill API test to set a new stakeholder 

### ISSUE THREAD

**Issue by cduhn17** [cisagov/pe-reports#213]
# 💡 Summary #

What is the work, as a high-level summary?

Create additional pytest to test the Cybersixgill API through the Flask customer UI

The test belongs because there are not tests that test the API for positive responses.

## Implementation notes ##

- Examine "def setNewCSGOrg" for a response['id'], for the process of setting a new stakeholder to be successful a response['id'] should be present to continue.

## Acceptance criteria ##

How do we know when this work is done?

- [ ] A new stakeholder will be created and can be verified by a response code of '200' at the end of function 'def stNewCSGOrg'

**Comment by rapidray12** [comment]
Included in PR 115
