### ISSUE TITLE
Verify reports email sent (Delivery Receipt)

### ISSUE THREAD

**Issue by cduhn17** [cisagov/pe-reports#216]
# 💡 Summary #

Add to the pe-reports-mailer to verify that all reports successfully sent and report to user successes and failures

## Motivation and context ##

As the project scales up it will be difficult to verify that all reports were sent by just looking at which reports were sent. 

Currently we are relying on an operator to manually look for the sent emails for each stakeholder.

## Implementation notes ##

Create python script to parse any log to verify if a 200 code was returned after sent report and read email header to know the email was passed off successfully to desired domain.

## Acceptance criteria ##

How do we know when this work is done?
- [ ] Create variables that reflect a positive and negative return code
- [ ] Get all return codes after email sent
- [ ] Determine methods to handle negative return codes and associated email to get to a positive return code after sending
- [ ] Report to system that all reports were sent successfully

**Comment by cduhn17** [comment]
@stewartl97 @rapidray12 
Do we care if we know anything more than if the email got handed to the correct domain successfully? Im thinking we can update this issue if that is all we care about, to zero in on the scope of this issue a bit more.

**Comment by aloftus23** [comment]
Closing but want to keep on the radar. @rapidray12
