### ISSUE TITLE
Update UI to setup all assets of an org from one form

### ISSUE THREAD

**Issue by DJensen94** [cisagov/pe-reports#234]
# 💡 Summary #
Add new UI page to fully setup orgs assets.
## Motivation and context ##
We currently have a UI form that sets up the cyhy assets but doesn't set up all the other portions we need to run all of our scans
This will greatly simplify setup 
## Implementation notes ##
We will add a new page that has a form that takes in the required information for the stakeholder.
It will then enumerate sub_domains and ips for the org and setup the accounts in cybersix
## Acceptance criteria ##

- [ ] New UI page is created
- [ ] Page has a form to launch stakeholder insert functions
- [ ] page has additional buttons to launch other scans that are necessary for stakeholder asset management i.e. link subs and ips

**Comment by DJensen94** [comment]
Successfully added form and ips_link button, though still may add some other functions to launch additional setup and and maintenance scans

**Comment by DJensen94** [comment]
The UI adjustments have been made, however if any of the scripts takes more than 30 minutes they close when run from the UI, needs to managed through celery to make sure they complete.

**Comment by stewartl97** [comment]
@DJensen94 let's go ahead and close this and create a bug ticket for the issue you listed concerning timeouts.
