### ISSUE TITLE
Research PDF creation alternatives to xhtml2pdf

### ISSUE THREAD

**Issue by DJensen94** [cisagov/pe-reports#239]
# 💡 Summary #
Looking into alternative libraries to generate pdfs for our reports
## Motivation and context ##
Xhtml2pdf struggles with many of the new features of html5, we want to look into alternative reporting libraries to implement more robust features into our reports

## Implementation notes ##
Test various libraries to see which have the features we need to build out our reports
## Acceptance criteria ##
We will have identified a new pdf generation library/process
or determined there is not a better alternative

**Comment by DJensen94** [comment]
looked into reportlab, but it was too granular (it is actually the base code for the current report generator

**Comment by DJensen94** [comment]
tested out pdfkit, it has a few quarks especially with headers, but overall it is a lot simpler to set up and works better with newer html features. I have built out the Bulletin generator using pdfkit, overall its working pretty well with a few quirky things with the headers

**Comment by stewartl97** [comment]
Identified Tableau as the report generator of choice.
