### ISSUE TITLE
Replace eval() functions

### ISSUE THREAD

**Issue by schmelz21** [cisagov/pe-reports#24]
# 🐛 Summary #

Python has an eval() function which evaluates a string of Python code `bandit` check has "blacklisted" as an insecure function.

## To reproduce ##

1. Run branch pre-commit: https://github.com/cisagov/pe-reports/tree/AL-working-v1.0

## Expected behavior ##

A `pre-commit run --all-files` should render no `bandit` errors.

## Any helpful log output or screenshots ##

Example Test Error:

```
Test results:
>> Issue: [B307:blacklist] Use of possibly insecure function - consider using safer ast.literal_eval.
   Severity: Medium   Confidence: High
   Location: src/pe_reports/report_metrics.py:191
   More Info: https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b307-eval
191                 k = eval(row["right"])
```

**Comment by cduhn17** [comment]
This issue was merged into develop branch per PR#31
