### ISSUE TITLE
Add functionality to the UI to support PE Bullitens

### ISSUE THREAD

**Issue by rapidray12** [cisagov/pe-reports#241]
# 💡 Summary #

Add functionality to the UI to support PE bullitens

## Motivation and context ##

As we grow PE Bulletins will become more prevalent. We need and easy (less time consuming) way to generate one off bullitens 

## Implementation notes ##

Please provide details for implementation, such as:

- It will be used to create one off bulletins
- Should be able to pull individual IDs from the vendor

## Acceptance criteria ##

- [ ] UI Updated to allow for PE bulletins 
- [ ] Report Template should be a CISA Style

**Comment by DJensen94** [comment]
Bulletin Generators have been created for cybersix gill intel items and credential breaches for an org, these generators have been implemented into the UI and pushed to staging
