### ISSUE TITLE
Ad-Hoc Branch Cleanup

### ISSUE THREAD

**Issue by stewartl97** [cisagov/pe-reports#245]
# 💡 Summary #

Ad-hoc has collected a lot of experimental and one time use code.  This needs to either be merged in, or removed.  The branch will then be renamed to Staging.  

## Motivation and context ##

This will simplify our internal deployment process and ensure that our team knows what code to avoid making changes to without extreme care and consideration.

## Implementation notes ##

- To provide a common space where code that is ready to be submitted for final approval by the Fusion Team will exist

## Acceptance criteria ##

- [x] Ad-hoc code has been managed.
- [x] Branch renamed to Staging

**Comment by cduhn17** [comment]
All, 
All `adhoc` features have had branches created with PR's to follow. The name 'adhoc' has been removed from staging environment and replaced with 'staging' and renamed in `pe-reports` repo. All local branches on local machines if left intact will need to run the following to mirror the GH branch name change: 
`git branch -m old_branch new_branch         # Rename branch locally
git push origin :old_branch                 # Delete the old branch
git push --set-upstream origin new_branch   # Push the new branch, set local branch to track the new remote`
future clones will come down with the correct branch name.
