### ISSUE TITLE
Command Line Functionality Documentation

### ISSUE THREAD

**Issue by stewartl97** [cisagov/pe-reports#26]
# 💡 Summary #

Update the GitHub SOP and associated documentation with the updated functionality.

## Acceptance criteria ##

How do we know when this work is done?

- [x] Update Teams Documentation - P&E GitHub SOP

This is related to #8

**Comment by aloftus23** [comment]
Added a quickstart guide so that anyone on the team can:
- clone this repo
- setup a virtual environment
- pass all pytest and pre-commits 

PE Teams Documents

**Comment by schmelz21** [comment]
Review and SOP is up to date with CMD Line usage and also additionally a "Quick Start" section.
