### ISSUE TITLE
Command Line Functionality - Matplotlib Default Log Level

### ISSUE THREAD

**Issue by stewartl97** [cisagov/pe-reports#27]
# 💡 Summary #
Default Log Level used by matplotlib is too verbose.  
usage:
pe-reports REPORT_DATE DATA_DIRECTORY OUTPUT_DIRECTORY [--db-creds-file=FILENAME] [--log-level=LEVEL]

## Implementation notes ##

Please provide details for implementation, such as:

To avoid Matplotlib INFO logs which can be extensive set --log-level=warning or anything not "info" pr default.

## Acceptance criteria ##

How do we know when this work is done?

- [ ]  Test test_log_levels(level) in test_pe_reports.py passes.

**Comment by cduhn17** [comment]
@stewartl97 
I think we need to revisit this as a group to determine desired log level, which impacts how much logging takes place. Thoughts?
