### ISSUE TITLE
Add useful test to pe-report module, develop branch

### ISSUE THREAD

**Issue by schmelz21** [cisagov/pe-reports#3]
Since you created dummy tests here, please create an issue in this repo to replace these tests with useful tests.  Then add a `TODO` comment somewhere in this file with a brief note and a link to the issue you created.

_Originally posted by @dav3r in https://github.com/cisagov/pe-reports/pull/2#discussion_r643465303_

**Comment by stewartl97** [comment]
@schmelz-ctr will most likely need your help to translate.  I suspect @cduhn17 will be able to handle this, but we should talk about it first.

**Comment by schmelz21** [comment]
@cduhn17 this particular issue still needs to develop while we build out the css/html to pdf solution. It was a dev-standard that we included "some tests" prior to merging code into `develop` branch. That was satisfied by adjusting some of the [python-skeleton](https://github.com/cisagov/skeleton-python-library) tests for pe-reports. While we continue to sunset Reports 0.1.1 and build out Reports 1.0.0, it will be expected of us to include "useful tests" in our code while we develop.

Early on @elr64 had worked on some that may apply to some of the cyhy db connection functions. We can possible explore those at some point.
