### ISSUE TITLE
Report QA: Confirm assets via WhoIs service

### ISSUE THREAD

**Issue by schmelz21** [cisagov/pe-reports#30]
# 💡 Summary #

A secondary check/script is needed to validate data feeds which include a list of a customer's assets. A "net-range validation process" or "whois" check is needed to filter bad assets.

## Motivation and context ##

This improves the quality of the report through validation and cuts down on any speculative data included in the reports.

## Implementation notes ##

Please provide details for implementation, such as:

- Define Solution

## Acceptance criteria ##

How do we know when this work is done?

- [ ] IP Addresses should be pulled from the CyHy database instead of LG to identify IP Addresses that are valid for the particular agency.
- [ ] The team should be able to perform asset checks on a regular basis to determine if the current IP addresses on record with CyHy are valid.

**Comment by cduhn17** [comment]
@schmelz21 @stewartl97 
I see in the cyhyDB there are network subnets associated with each agency. Is it in scope of this issue to search through the subnets that are associated with each agency?

**Comment by schmelz21** [comment]
@cduhn17, to me the process you suggest is in scope to the request and would compliment any domain/ip lookup processes to validate assets in the network. I am assuming cyhyDB --> WhoIs == Valid and Invalid
Yield to @stewartl97

**Comment by cduhn17** [comment]
@schmelz21 
Im including all cidr noted ip blocks. Also rolling in the LG ip addresses(one time basis) will check the ip's whenever the scans run in the future.

**Comment by cduhn17** [comment]
WHOIS data service has been in use and merged into develop(unsure of PR#).
