### ISSUE TITLE
Setup Tableau Server in the Accessor

### ISSUE THREAD

**Issue by DJensen94** [cisagov/pe-reports#303]
In order to generate PDF Tableau reports we need a Tableau Server stood up. The best place for this will be in our accessor so it can access our database

**Comment by cduhn17** [comment]
Not a viable option at this time.

**Comment by rapidray12** [comment]
After looking at the existing Tableau server it became apparent that it would be too tough to use for our purposes.

**Comment by cduhn17** [comment]
This effort is tabled for now, so closing the issue
