### ISSUE TITLE
Dynamic Appendicies To Add Descriptive Details

### ISSUE THREAD

**Issue by stewartl97** [cisagov/pe-reports#32]
# 💡 Summary #

Our report needs to have context when displaying source information such as Forum Name or Breach Names.

## Motivation and context ##

This is best done in an appendix as the tables used in the report are too small to give enough detail about a given item.

## Implementation notes ##

The appendices should be dictionary style in nature.  This allows our users to quickly identify the information and read a short 1 - 2 sentence summary.

## Acceptance criteria ##

How do we know when this work is done?

- [x] Breach Desceription Appendix
- [ ] Dark Web Site Appendix
- [ ] Dark Web/Deep Web Site Appendix
- [ ] Appendicies should be dynamic and only display information contained in the report.

**Comment by DJensen94** [comment]
Breach appendix has been added, but Dark Web has not, still need to look into this

**Comment by aloftus23** [comment]
Closing. Not relevant anymore with Report Lab
