### ISSUE TITLE
Dark Web Database Schema

### ISSUE THREAD

**Issue by aloftus23** [cisagov/pe-reports#35]
# 💡 Summary #

Show database schema for domain masquerading data

## Motivation and context ##

To support database creation and use. For now, will be used solely for the rest of the team to referance.

## Implementation notes ##

- create at least one table that emulates how the data will be stored
- add to the data_schema.sql file located [here](https://github.com/cisagov/pe-reports/tree/develop/src/pe_reports/data)

## Acceptance criteria ##

- [ ] At least one table is created
- [ ] Each field needed for the report is included
- [ ] Table is commented out

**Comment by schmelz21** [comment]
![Scheme](https://user-images.githubusercontent.com/81192860/130859503-e67912da-0a28-4711-8b25-6391877bf090.png)
Current dark web scheme for review.
