### ISSUE TITLE
Make sure containers are not running as root

### ISSUE THREAD

**Issue by aloftus23** [cisagov/pe-reports#357]
# 💡 Summary #

Make sure all container processes are not running as root.

## Motivation and context ##

https://medium.com/@mccode/processes-in-containers-should-not-run-as-root-2feae3f0df3b

**Comment by cduhn17** [comment]
I think as long as the docker daemon isnt running as root we are good to go. Is that what @aloftus23 understand to be the way we want to run our container services?
