### ISSUE TITLE
Research Harvester Integration with IntelX

### ISSUE THREAD

**Issue by aloftus23** [cisagov/pe-reports#375]
# 🐛 Summary #

Harvester offers an integration with intelx. Research if this will be helpful to support ASM capabilities such as collecting IPs, subdomains, and other asset information.

**Comment by cduhn17** [comment]
@aloftus23 
How do these capabilities support collecting IPs, subdomains, and other asset information? We might add some more information of why we are doing this research and what expected results might come from this integration and the resulting expected impacts to the project.

**Comment by aloftus23** [comment]
Overview:
[Harvester](https://github.com/laramies/theHarvester)

theHarvester gathers OSINT intelligence for red team recon (names, emails, IPs, subdomains, and URLs). Allows you to search a domain on many different sources such as hunter, shodan, intelx, etc. However, you can only search one source at a time, and many either don't contain relevant results or require an API key. Also, many of the sources aren't up to date with the latest versions.

Conclusion:
 theHarvester can be a good resource for finding new sources to look into, but you are better off finding better results and the latest updates directly from the source.
