### ISSUE TITLE
Set up ELK on AWS

### ISSUE THREAD

**Issue by RoddyFJ** [cisagov/pe-reports#377]
# 💡 Summary #

Containerize and set up Elasticsearch on AWS

## Motivation and context ##

Use ELK to monitor Status of running applications and log files to allow for expansion of users

## Implementation notes ##

Set up docker compose file to allow for instant setup of ELK cluster that can be reused for later operations

## Acceptance criteria ##

ELK is running on AWS in some fashion

- [x] Local Setup
- [x] VM Working
- [ ] AWS Working

**Comment by RoddyFJ** [comment]
Elastic On Ubuntu

Need to increase vm.max_map_count

echo vm.max_map_count=262144 >> /etc/sysctl.conf 
sudo sysctl -p

**Comment by stewartl97** [comment]
@RoddyFJ  @rapidray12  Can we get an update for this ticket?

**Comment by RoddyFJ** [comment]
Got full stack working on VM. Now working on pulling Jango logs to monitor the new API

**Comment by RoddyFJ** [comment]
Closing this ticket to make more nuanced tickets to better reflect the Project
