### ISSUE TITLE
Suspected Vulnerabilities Database Schema

### ISSUE THREAD

**Issue by aloftus23** [cisagov/pe-reports#39]
# 💡 Summary #

Show database schema for domain masquerading data

## Motivation and context ##

To support database creation and use. For now, will be used solely for the rest of the team to reference.

## Implementation notes ##

- create at least one table that emulates how the data will be stored
- add to the data_schema.sql file located [here](https://github.com/cisagov/pe-reports/tree/develop/src/pe_reports/data)

## Acceptance criteria ##

- [x] At least one table is created
- [x] Each field needed for the report is included
- [ ] Tables are commented out

**Comment by schmelz21** [comment]
Closing per PR https://github.com/cisagov/pe-reports/pull/70 - https://github.com/cisagov/pe-reports/pull/70#issuecomment-931296545
