### ISSUE TITLE
Add Windows option to convert a .pptx file to a .pdf.

### ISSUE THREAD

**Issue by schmelz21** [cisagov/pe-reports#4]
# 💡 Summary #
Current solution uses LibreOffice to convert PowerPoint Presentation to a PDF file. This works well for both Mac OSX and Linux systems. A possible code modification could be made to include Windows operating systems.

## Motivation and context ##
This is a critical process in producing an encrypted PDF for a customer. This would be useful for persons using a Windows operating system.

## Implementation notes ##

To implement write in a condition to check system OS:
if os.name == ''posix':
linuxStuff()
elif os.name == 'nt':
windowsStuff()
elif os.name == 'os2': ...

If Windows use WIN COM, not LibreOffice to convert pptx to pdf. The user must have PowerPoint installed.

from pathlib import Path
import win32com.client

def ppt2pdf(ppt_target_file):
    file_path = Path(ppt_target_file).resolve()
    out_file = file_path.parent / file_path.stem
    powerpoint = win32com.client.Dispatch("Powerpoint.Application")
    pdf = powerpoint.Presentations.Open(file_path, WithWindow=False)
    pdf.SaveAs(out_file, 32)
    pdf.Close()
    powerpoint.Quit()

ppt2pdf('<The Presentation.pptx>')

## Acceptance criteria ##

How do we know when this work is done?

- [ ] Can be run on Windows OS.
- [ ] README.md Installation instructions address the option.

**Comment by stewartl97** [comment]
@schmelz-ctr is this particular issue OBE?  I don't see any reason to continue development on this branch as it will become deprecated soon.  Would it make sense to make it a requirement for the P&E 1.0 branch?

**Comment by schmelz21** [comment]
@stewartl97, yes your correct. I can't see it being applied to P&E 1.0 due to there should be no operating system dependancies at this time or foreseeable future. Closing the Issue.
