### ISSUE TITLE
Define `libreoffice_exe()` failure outcome

### ISSUE THREAD

**Issue by cduhn17** [cisagov/pe-reports#40]
# 💡 Summary #

At the function libreoffice_exec() What happens in this code if sys.platform == "darwin" is false?
`def libreoffice_exec():
    """Call to MacOS LibeOffice App."""
    if sys.platform == "darwin":
        return "/Applications/LibreOffice.app/Contents/MacOS/soffice"`

## Motivation and context ##

The failure of this function will stop the execution of the program.

This would be useful because not only would the program finish with a return value of 0. 

The improvement could make it possible to run the software on other OS versions.

## Acceptance criteria ##

How do we know when this work is done?

- [ ] Return value 0 on completion of program
- [ ]  Alternative functionality to launch Libreoffice regardless of OS version or environment

**Comment by stewartl97** [comment]
@cduhn17 @schmelz-ctr I was under the impression we moved away from libreoffice for report generation.  Is that not true?

**Comment by schmelz21** [comment]
@stewartl97 it still used in Report 0.1.1. version ... branch `main`. I believe this issue was brought to attention from Fusion Dev during one of our PRs to take a look during cleanup.

**Comment by cduhn17** [comment]
@stewartl97 
Its remains in 0.1.1 but as I understand gets eliminated in 1.0
@schmelz-ctr 
Yes dev fusion made mention and that is where this where issue # 40 came from.

**Comment by schmelz21** [comment]
@stewartl97 @cduhn17 - yes gone in 1.0.0.. 
In pe-mailer PR, this is what we are looking at as far as dependancies and run - [See README](https://github.com/cisagov/pe-reports/tree/wip_pe-mailer). Should be able to through in container if need be..

**Comment by schmelz21** [comment]
Closing pull-request as efforts to update the main branch have been canceled. Routines used in version 0.1.1 have been sunsetted with no future plans to update.
