### ISSUE TITLE
Develop & Implement WAS Score

### ISSUE THREAD

**Issue by arng4108** [cisagov/pe-reports#405]
# 💡 Summary #

Create an overall score for the WAS team (like the PE and VS scores).

## Motivation and context ##

Each CyHy team (PE, VS, WAS, PCA) needs an overall score 0-100 to be used in the overall CyHy scorecard. Currently, only PE and VS have scores, so a WAS score needs to be developed

## Implementation notes ##

- Score must be 0-100 (capable of conversion to letter grade and averaging with other scores)
- Score must act as an overall summation of WAS findings
- Score will have to be generated even if WAS report schedule is different from PE

## Acceptance criteria ##

- [X] General layout of WAS score developed
- [X] Figured out how to gather necessary data for WAS score
- [X] Implemented WAS score in python
- [ ] Connected to DB via API and tested for correct functionality

**Comment by claires8** [comment]
No longer doing tis in favor of DPIT scores
