### ISSUE TITLE
DRY out this code (PE Report 0.1.1)

### ISSUE THREAD

**Issue by schmelz21** [cisagov/pe-reports#41]
# 💡 Summary #

This Issue has been split for both PE Report 0.1.1 "`main`" and for PE Report 1.0.0 "`develop`" -  Issue #18,  as both repos need updated, but constitute separate efforts.

There is a repeat pattern of code used in pages.py. Noted in comments bug-unusable-package, [here](https://github.com/cisagov/pe-reports/pull/6#discussion_r672827066) and [here ](https://github.com/cisagov/pe-reports/pull/6#discussion_r672827816) The code should be re-written as a single function/class, unambiguous and non-repeatable.

Please provide details for implementation, such as:

- An evaluation of updated Matplotlib code to pptx file code is needed.
- Remove repetitive code - standardize graphing output.

## Acceptance criteria ##

How do we know when this work is done?

- [ ] Repetition of code is reduced.

**Comment by cduhn17** [comment]
This reference to 'dry out code' was relevant prior to PR#31 and has been addressed per PR#31.
