### ISSUE TITLE
Add CyHy Scorecard to UI and make data available via REST API 

### ISSUE THREAD

**Issue by cduhn17** [cisagov/pe-reports#425]
# 💡 Summary #

First step toward dynamic generator of scorecard for all stakeholder
Add api endpoint to get json data of data contained in scorecard

## Motivation and context ##

To get most updated scorecard and ability to deliver raw json data

## Implementation notes ##

Please provide details for implementation, such as:

- an example for how this would be used
- what this would look like
- how this would act
- any related work, including links to related issues

## Acceptance criteria ##

How do we know when this work is done?

- [ ] UI webapp page
- [ ] Api endpoint to get raw data that went into report creation

**Comment by stewartl97** [comment]
Not needed due to ticket tracking individual endpoints
