### ISSUE TITLE
Remove hard-coded file locations

### ISSUE THREAD

**Issue by schmelz21** [cisagov/pe-reports#45]
# 💡 Summary #

In Pages Class remove hard-coded references to files. 

## Motivation and context ##

This would be useful because it removes any directory management issues. 
Code Example:
`df_customer = pd.read_csv("src/pe_reports/data/csv/dhs_customer.csv")`

## Implementation notes ##

- Create a data-dictionary reference or method to resolve file paths in class.
## Acceptance criteria ##

How do we know when this work is done?

- [ ] Remove hard-coded file paths
- [ ] pe-reports passes checks and run

**Comment by cduhn17** [comment]
This issue has become irrelevant due to access to a DB at the cool and the use of csv files for data access does not exist in the develop branch.
