### ISSUE TITLE
"install_requires" package to create a CyHy MongoDB connection

### ISSUE THREAD

**Issue by schmelz21** [cisagov/pe-reports#46]
# 🐛 Summary #

PE Reports and eventually the PE Mailer processes rely on including the package from [mongo-db-from-config](https://github.com/cisagov/mongo-db-from-config/). The current implementation in. `setup.py` in branch [ss-working-tests](https://github.com/cisagov/pe-reports/blob/4be58e3a38217e186b22d151f7d4a024c84a5952/setup.py#L94) adds this requirement yet fails on install. Also attempted was the following taken from the [cyhy-mailer](https://github.com/cisagov/cyhy-mailer/blob/2438501ea492798c481e0617d7ad1353345c63ea/setup.py#L56) repo:
`        "mongo-db-from-config @ http://github.com/cisagov/mongo-db-from-config/tarball/develop#egg=mongo-db-from-config"
`

Question: Is there additional code or method that's need to be included, or alternatively is this now a step added to install instructions.

## To reproduce ##

1. `pe-reports % python3 setup.py install`
2. Then this:
`ModuleNotFoundError: No module named 'mongo_db_from_config'`

## Expected behavior ##

What did you expect to happen that didn't?

The `mongo-db-from-config` package installs on setup.

**Comment by schmelz21** [comment]
@dav3r I'm assuming you have seen this one once or twice.
Thanks

**Comment by jsf9k** [comment]
I'll take a look now.

**Comment by dav3r** [comment]
I just ran the following commands in a clean virtual environment and the `mongo_db_from_config` package was installed as expected:

```console
./setup-env   # use --force if you want to start with a fresh virtualenv
python
>>> import mongo_db_from_config
>>> mongo_db_from_config.__version__
'0.0.1'
```

I also was able to run `python3 setup.py install` without seeing the error that you described.

@schmelz-ctr - Are you using the `setup-env` script to set up your virtual environment [as described in CONTRIBUTING.md](https://github.com/cisagov/pe-reports/blob/develop/CONTRIBUTING.md#setting-up-pre-commit)?  It's very helpful for simplifying the setup of a functional Python virtual environment.

**Comment by schmelz21** [comment]
@dav3r, I will revisit the  `setup-env` as it may be my issue. Will test following those steps and report back.

**Comment by dav3r** [comment]
Also, in `setup.py`, I'm pretty sure you can safely replace:
```
"mongo-db-from-config @ https://github.com/cisagov/mongo-db-from-config/tarball/develop",
```
with
```
"mongo-db-from-config @ git+https://github.com/cisagov/mongo-db-from-config",
```
but @jsf9k or @mcdonnnj should probably double-check me on that.

**Comment by jsf9k** [comment]
@dav3r - why would you do that?

**Comment by jsf9k** [comment]
> Also, in `setup.py`, I'm pretty sure you can safely replace:
> 
> ```
> "mongo-db-from-config @ https://github.com/cisagov/mongo-db-from-config/tarball/develop",
> ```
> 
> with
> 
> ```
> "mongo-db-from-config @ git+https://github.com/cisagov/mongo-db-from-config",
> ```
> 
> but @jsf9k or @mcdonnnj should probably double-check me on that.

Why would you do that?  That breaks the "normal" installation as described [here](https://github.com/cisagov/pe-reports/issues/46#issuecomment-911718006).

**Comment by jsf9k** [comment]
I was able to reproduce @schmelz-ctr's issue from a fresh checkout with these commands:
```bash
$ pyenv virtualenv 3.9.7 pe-reports  # I also tried 3.7.9
$ pyenv local pe-reports
$ python3 setup.py install
```

That `python3 setup.py install` command is very old fashioned I think.  The install works fine with `pip install -e .` or `pip install .`, which I think is what you should be using anyway.  I think that's the resolution here.

**Comment by dav3r** [comment]
> > Also, in `setup.py`, I'm pretty sure you can safely replace:
> > ```
> > "mongo-db-from-config @ https://github.com/cisagov/mongo-db-from-config/tarball/develop",
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > with
> > ```
> > "mongo-db-from-config @ git+https://github.com/cisagov/mongo-db-from-config",
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > but @jsf9k or @mcdonnnj should probably double-check me on that.
> 
> Why would you do that?

Slightly shorter syntax and I think it's the same thang, but if I'm mistaken, please let me know.  Nevermind- I just saw your edited comment above.  Suggestion withdrawn!

**Comment by schmelz21** [comment]
@dav3r, @jsf9k,
Originally was building my virtual environment via VS Code method. Obviously this approach did not handle the `tar.gz` install properly, but seems to trace back to using` pe-reports % python3 setup.py install`.
Example:
```
pe-reports % python3 -m venv .venv
pe-reports % source .venv/bin/activate
pe-reports % python3 setup.py install
```
But after reviewing comments the following worked:

1. Install venv via [CONTRIBUTING.md](https://github.com/cisagov/pe-reports/blob/develop/CONTRIBUTING.md#setting-up-pre-commit) method (`./setup-env --force`):
>` pe-reports %  pip install --requirement requirements-dev.txt`

2. Install venv via VS Code method :
```
pe-reports % python3 -m venv .venv
pe-reports % source .venv/bin/activate
pe-reports % pip install -e .
```
or
```
pe-reports % python3 -m venv .venv
pe-reports % source .venv/bin/activate
pe-reports % pip install .
```
**_Both answers satisfied the issue, and will close._**

As far as setup.py `install_requires=[]`:
- works =` "mongo-db-from-config @ http://github.com/cisagov/mongo-db-from-config/tarball/develop#egg=mongo-db-from-config"`
- works = ` "mongo-db-from-config @ http://github.com/cisagov/mongo-db-from-config/tarball/develop"`
- doesn't work = `"mongo-db-from-config @ http://github.com/cisagov/mongo-db-from-config"`
