### ISSUE TITLE
Primary Key integer or UUID

### ISSUE THREAD

**Issue by cduhn17** [cisagov/pe-reports#49]
# 💡 Summary #

Should the db schema implement int or UUID as the primary key in a table

## Motivation and context ##

In the event that the relationships grow in complexity and the possibility of scaling the DB to a data warehouse

The chance of orphaned data relationships is diminished when scaling out the data

## Implementation notes ##

Please provide details for implementation, such as:

- Change the primary key type from integer to UUID

## Acceptance criteria ##

How do we know when this work is done?

- [ ] primary key type changed from int to UUID

**Comment by cduhn17** [comment]
@stewartl97 @schmelz-ctr @elr64 @aloftus23 @DJensen94 

Thoughts on setting primary key types to UUID in-place of type INT? Are there scalability concerns if the PE reports data at some point is transferred into a data warehouse?

**Comment by schmelz21** [comment]
@cduhn17 If you take into consideration any long term goals/planning where we may be doing "trends" or "investigations" over a year(s), it makes sense to implementing something scalable. I'd be for it...

Here is a little blog mentioning the pros and cons: https://tomharrisonjr.com/uuid-or-guid-as-primary-keys-be-careful-7b2aa3dcb439

**Comment by schmelz21** [comment]
I noticed as we build out sql, we are missing any timestamps in relation to record creation.  Another thought, as I can see this issue morphing into a final cleanup "Task" of all our schema PRs. I linked to pull request related to this topic in the event someone gets designated to give a final pass-though.

**Comment by schmelz21** [comment]
Closing due to PR - "Replace id column data type" #59
