### ISSUE TITLE
Package is not Usable

### ISSUE THREAD

**Issue by mcdonnnj** [cisagov/pe-reports#5]
# 🐛 Summary #

As of the merge of #2 this project is unusable. Trying to perform `import pe_reports` results in:

```console
>>> import pe_reports
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mcdonnnj/workspace/cisa_repos/pe-reports/src/pe_reports/__init__.py", line 7, in <module>
    from _version import __version__  # noqa: F401
ModuleNotFoundError: No module named '_version'
```

## To reproduce ##

1. Clone the repo
1. Set up Python environment
1. Install package
1. Perform an `import pe_reports` either in a script or the Python interactive shell

## Expected behavior ##

An `import pe_reports` call is performed with no errors.

## Suggested resolution ##

I performed a review of #2 which can be found here https://github.com/cisagov/pe-reports/pull/2#pullrequestreview-676687765. The issues mentioned should be resolved. In addition a bare minimum of testing _**must**_ be implemented along the lines of [this section of the tests in cisagov/skeleton-python-library](https://github.com/cisagov/skeleton-python-library/blob/4ef2364701c0db074c423f740062b2d7c197bea8/tests/test_example.py#L36-L62). This will guarantee that before any merges the changes clear both linters (through pre-commit) and enough testing to show that it is a bare-minimum functional Python package.

**Comment by schmelz21** [comment]
@mcdonnnj closing this issue due to successful merge and resolution on PR - https://github.com/cisagov/pe-reports/pull/6
