### ISSUE TITLE
mypy hook: PyYAML not supported with Python 3.9

### ISSUE THREAD

**Issue by schmelz21** [cisagov/pe-reports#52]
# 🐛 Summary #

During run of `pre-commit run --all-flies` mypy check issues the following warning: "PyYAML not supported with Python 3.9"

## To reproduce ##

1. Have `import yaml ` in scripts. [PyPi Reference](https://pypi.org/project/PyYAML/)
2. `pre-commit run --all-flies`

## Expected behavior ##

- pre-commit would pass after implementing the following parameter to `mypy` hook - additional_dependencies: [types-all]
- Reference: https://github.com/asottile/types-all

**Comment by jsf9k** [comment]
@schmelz-ctr, you want to add [this sort of thing](https://github.com/cisagov/hash-http-content/blob/develop/.pre-commit-config.yaml#L107-L112)  to `.pre-commit-config.yaml` and [this sort of thing](https://github.com/cisagov/skeleton-python-library/pull/82/commits/3452b9de398c48d73f06d2fecc666d07341a9038) to `setup-env`.

**Comment by schmelz21** [comment]
@jsf9k yes, I was looking at updating the` .pre-commit-config.yaml`and can use what was provided. Thanks.

**Comment by schmelz21** [comment]
@jsf9k so looks like we were up to date with Lineage PR suggested for `setup-env`. However I am getting a mypy error with [this sort of thing](https://github.com/cisagov/hash-http-content/blob/develop/.pre-commit-config.yaml#L107-L112) in `.pre-commit-config.yaml` with error:

```
mypy.....................................................................Failed
- hook id: mypy
- exit code: 1

src/pe_reports/report_generator.py:28: error: Library stubs not installed for "pkg_resources" (or incompatible with Python 3.9)
src/pe_reports/report_generator.py:28: note: Hint: "python3 -m pip install types-setuptools"
src/pe_reports/report_generator.py:28: note: (or run "mypy --install-types" to install all missing stub packages)
src/pe_reports/report_generator.py:28: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
src/pe_mailer/email_reports.py:18: error: Library stubs not installed for "yaml" (or incompatible with Python 3.9)
src/pe_mailer/email_reports.py:18: note: Hint: "python3 -m pip install types-PyYAML"
Found 2 errors in 2 files (checked 15 source files)

```

What does seem to work instead is this.. 
```
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        additional_dependencies:
          - types-setuptools
          - types-all
```

Can you confirm or is there other dependancies missing? 
I pushed the suggestion for viewing purposes...

**Comment by jsf9k** [comment]
> @jsf9k so looks like we were up to date with Lineage PR suggested for `setup-env`. However I am getting a mypy error with [this sort of thing](https://github.com/cisagov/hash-http-content/blob/develop/.pre-commit-config.yaml#L107-L112) in `.pre-commit-config.yaml` with error:
> 
> ```
> mypy.....................................................................Failed
> - hook id: mypy
> - exit code: 1
> 
> src/pe_reports/report_generator.py:28: error: Library stubs not installed for "pkg_resources" (or incompatible with Python 3.9)
> src/pe_reports/report_generator.py:28: note: Hint: "python3 -m pip install types-setuptools"
> src/pe_reports/report_generator.py:28: note: (or run "mypy --install-types" to install all missing stub packages)
> src/pe_reports/report_generator.py:28: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
> src/pe_mailer/email_reports.py:18: error: Library stubs not installed for "yaml" (or incompatible with Python 3.9)
> src/pe_mailer/email_reports.py:18: note: Hint: "python3 -m pip install types-PyYAML"
> Found 2 errors in 2 files (checked 15 source files)
> ```
> 
> What does seem to work instead is this..
> 
> ```
>   - repo: https://github.com/pre-commit/mirrors-mypy
>     rev: v0.910
>     hooks:
>       - id: mypy
>         additional_dependencies:
>           - types-setuptools
>           - types-all
> ```
> 
> Can you confirm or is there other dependancies missing?
> I pushed the suggestion for viewing purposes...

You probably need to add [`types-PyYAML`](https://pypi.org/project/types-PyYAML/) to `.pre-commit-config.yaml`.

**Comment by schmelz21** [comment]
> > @jsf9k so looks like we were up to date with Lineage PR suggested for `setup-env`. However I am getting a mypy error with [this sort of thing](https://github.com/cisagov/hash-http-content/blob/develop/.pre-commit-config.yaml#L107-L112) in `.pre-commit-config.yaml` with error:
> > ```
> > mypy.....................................................................Failed
> > - hook id: mypy
> > - exit code: 1
> > 
> > src/pe_reports/report_generator.py:28: error: Library stubs not installed for "pkg_resources" (or incompatible with Python 3.9)
> > src/pe_reports/report_generator.py:28: note: Hint: "python3 -m pip install types-setuptools"
> > src/pe_reports/report_generator.py:28: note: (or run "mypy --install-types" to install all missing stub packages)
> > src/pe_reports/report_generator.py:28: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
> > src/pe_mailer/email_reports.py:18: error: Library stubs not installed for "yaml" (or incompatible with Python 3.9)
> > src/pe_mailer/email_reports.py:18: note: Hint: "python3 -m pip install types-PyYAML"
> > Found 2 errors in 2 files (checked 15 source files)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > What does seem to work instead is this..
> > ```
> >   - repo: https://github.com/pre-commit/mirrors-mypy
> >     rev: v0.910
> >     hooks:
> >       - id: mypy
> >         additional_dependencies:
> >           - types-setuptools
> >           - types-all
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Can you confirm or is there other dependancies missing?
> > I pushed the suggestion for viewing purposes...
> 
> You probably need to add [`types-PyYAML`](https://pypi.org/project/types-PyYAML/) to `.pre-commit-config.yaml`.

Yes -  it is currently added in commit - https://github.com/cisagov/pe-reports/commit/7af4e493b6806d072736798b36aed9627c65d025
for review.

also referenced in `setup.py` `install_requires`

**Comment by jsf9k** [comment]
> Yes - it is currently added in commit - [7af4e49](https://github.com/cisagov/pe-reports/commit/7af4e493b6806d072736798b36aed9627c65d025)
> for review.
> 
> also referenced in `setup.py` `install_requires`

I don't see `types-PyYAML` mentioned in that commit.

**Comment by schmelz21** [comment]
> > Yes - it is currently added in commit - [7af4e49](https://github.com/cisagov/pe-reports/commit/7af4e493b6806d072736798b36aed9627c65d025)
> > for review.
> > also referenced in `setup.py` `install_requires`
> 
> I don't see `types-PyYAML` mentioned in that commit.

Oh my, I got it.  I originally thought you were making a 'straight-up' code suggestion with the examples. Sorry for the back and forth. I'm a little slow on the draw today... Updated  `.pre-commit-config.yaml` in this commit and looking to close issue. ac7c06d

**Comment by jsf9k** [comment]
> Oh my, I got it. I originally thought you were making a 'straight-up' code suggestion with the examples. Sorry for the back and forth. I'm a little slow on the draw today... Updated `.pre-commit-config.yaml` in this commit and looking to close issue. [ac7c06d](https://github.com/cisagov/pe-reports/commit/ac7c06d27971a20976eaebdaa69501cf6f9af56d)

No worries, it happens to us all.  I probably wasn't clear enough when I made the suggestion.  Glad we're on the same page now. :smile:
