### ISSUE TITLE
Figure out how to handle IPs that resolve to service providers

### ISSUE THREAD

**Issue by aloftus23** [cisagov/pe-reports#538]
# 💡 Summary #

IPs with ownership like Amazon, Akamai, etc. should be distinguished from IPs directly attributed to an organization.

Should we report on them at all?

Do we create separate charts and sheets in the raw data?

- [x] Schedule a meeting to discuss and update ticket

**Comment by edujosemena** [comment]
https://github.com/SecOps-Institute/Akamai-ASN-and-IPs-List/blob/master/akamai_ip_cidr_blocks.lst
