### ISSUE TITLE
VS API for IP ownership info

### ISSUE THREAD

**Issue by edujosemena** [cisagov/pe-reports#540]
# 💡 Summary #

To expand data-sharing with in within Cy-Hy we are going to create an API endpoint for them to be able to access the list of IPs that we have for each organization. 

## Motivation and context ##

This information sharing will be benefitial for reporting FCEB customers, all teams should be able to report the same information

## Implementation notes ##

Input Requirements
- The api should accept a list of IP addresses in IPv4 format.
- The api should be able to handle large volumes of IP addresses, up to 100,000.
- The api should accept ips through get request

Output Requirements
- The tool should return a table of results with the following columns: organization_uid, database name, and IP linked to org.
- The tool should be able to handle large volumes of output data, up to 500,000 rows.

Database Requirements

- The api will reference a view built to traverse organizations table from the ips table.

## Acceptance criteria ##

How do we know when this work is done?

- [x] Get requirements from the VS Team
- [x] Design The view to map informations from IP to organization table
- [x] Create API key for VS
- [x] Create endpoint for information
- [x] Runbook

**Comment by cduhn17** [comment]
This endpoint is complete and the run book has been forwarded to Keith on VS team
