### ISSUE TITLE
Elasticsearch on AWS Testing

### ISSUE THREAD

**Issue by RoddyFJ** [cisagov/pe-reports#544]
# 💡 Summary #

Set up the ELK docker cluster on AWS and test

## Motivation and context ##

Being able to host an ELK cluster on AWS will allow P&E to expand how many scans can run autonomously. Using ELK they can track what has been started, stopped or erred across multiple scans. Using AWS SNS and Kibana combined they can notify P&E members when there are critical errors on scans or even when scans have completed.

It will allow P&E to track API usage as they stand the APIs up. It should be able to track all logs and errors as they happen and using Kibana will be able to view it in graphical form. 

## Implementation notes ##

Fully Deploy on AWS
Pulling in logs 

## Acceptance criteria ##

How do we know when this work is done?

- [x]  ELK Docker on AWS
    - [x] Provision EC2 to be able to pull git
    - [x] Install docker-compose on EC2
    - [x] Pull GitHub to EC2 
- [x] Fully running ELK 
    - [x] Run full ELK on EC2 with no errors
    - [x] Log into kibana from P&E laptops 
- [x] Pulling in logs into system
    - [x] Pull in EC2 logs and metrics
    - [x] Create Fleetserver on ELK EC2
    - [x] Place elastic-agent onto PE-Reports EC2
    - [x] Recieve logs from pe-reports and django
    - [x] Access Accessor and pull in logs from scans running

**Comment by cduhn17** [comment]
ELK is up and running all containers, fleet server is configured and running on ELK EC2, Elastic-agent running on PE-Reports EC2

**Comment by cduhn17** [comment]
ELK is now getting all logs from pe functions that scan and from the Django app and APM on Django.

**Comment by cduhn17** [comment]
All items complete

**Comment by cduhn17** [comment]
All items are complete
