### ISSUE TITLE
POST Save summary statistics

### ISSUE THREAD

**Issue by cduhn17** [cisagov/pe-reports#558]
# 💡 Summary #

Add new REST endpoints that mirror existing sql queries and replace existing sql query with REST
Specifically: Convert "execute_scorecard(summary_dict)" TSQL query to an API endpoint

## Motivation and context ##

There are two major reasons to use endpoints in place of sql queries.
- Replace the need to know t-sql
- Off load data aggregation to fastapi parallel workers

## Implementation notes ##

- Gather existing queries from code.
- Create new endpoints at fastapi.
- Secure new endpoints in same fashion as existing endpoint.

## Acceptance criteria ##

- [ ] home/models.py model created
- [ ] dataAPI/schemas.py schema created
- [ ] dataAPI/views.py functions created
- [ ] dataAPI/tasks.py function created
- [ ] Verified endpoint is working

**Comment by arng4108** [comment]
Issue closed, replaced by issue #632
