### ISSUE TITLE
POST Insert the ips into the ips table

### ISSUE THREAD

**Issue by cduhn17** [cisagov/pe-reports#559]
# 💡 Summary #

Add new REST endpoints that mirror existing sql queries and replace existing sql query with REST
Specifically: Convert "execute_ips()" TSQL query to an API endpoint

Don't know which TSQL function this issue is referring to

## Motivation and context ##

There are two major reasons to use endpoints in place of sql queries.
- Replace the need to know t-sql
- Off load data aggregation to fastapi parallel workers

## Implementation notes ##

- Gather existing queries from code.
- Create new endpoints at fastapi.
- Secure new endpoints in same fashion as existing endpoint.

## Acceptance criteria ##

- [X] home/models.py model created
- [X] dataAPI/schemas.py schema created
- [X] dataAPI/views.py functions created
- [X] dataAPI/tasks.py function created
- [X] Verified endpoint is working

**Comment by arng4108** [comment]
This API endpoint has been completed, code reviewed, and added the CD-pe-reports-api-extended branch
