### ISSUE TITLE
POST Query cybersix_exposed_credentials table

### ISSUE THREAD

**Issue by cduhn17** [cisagov/pe-reports#561]
# 💡 Summary #

Add new REST endpoints that mirror existing sql queries and replace existing sql query with REST
Specifically: Convert "query_cyberSix_creds()" TSQL query to an API endpoint

## Motivation and context ##

There are two major reasons to use endpoints in place of sql queries.
- Replace the need to know t-sql
- Off load data aggregation to fastapi parallel workers

## Implementation notes ##

- Gather existing queries from code.
- Create new endpoints at fastapi.
- Secure new endpoints in same fashion as existing endpoint.

## Acceptance criteria ##

- [X] Cleaned up any traces of this unused function

**Comment by arng4108** [comment]
This endpoint queries a table in the database that no longer exists. Additionally, the function is not used anywhere. Therefore, this endpoint will not be converted/included in the API effort

**Comment by arng4108** [comment]
Reopening this issue to be revisited later, primarily to clean up any traces of this unused function. The function query_cyberSix_creds() is still not used anywhere, and the table it references does not exist.

**Comment by arng4108** [comment]
After searching through the staging branch, there are no traces of this function being used/called anywhere. Because of this, the api conversion of this TSQL function has not been added to staging. However, the api conversion remains on the api-extended branch just in case.
