### ISSUE TITLE
PUT insert Roots

### ISSUE THREAD

**Issue by cduhn17** [cisagov/pe-reports#564]
# 💡 Summary #

Add new REST endpoints that mirror existing sql queries and replace existing sql query with REST
Specifically: Convert "insert_roots()" TSQL query to an API endpoint

## Motivation and context ##

There are two major reasons to use endpoints in place of sql queries.
- Replace the need to know t-sql
- Off load data aggregation to fastapi parallel workers

## Implementation notes ##

- Gather existing queries from code.
- Create new endpoints at fastapi.
- Secure new endpoints in same fashion as existing endpoint.

## Acceptance criteria ##

- [X] home/models.py model created
- [X] dataAPI/schemas.py schema created
- [X] dataAPI/views.py functions created
- [X] dataAPI/tasks.py function created
- [X] Verified endpoint is working
- [X] pushed endpoint to api-extended

**Comment by arng4108** [comment]
Endpoint completed and pushed to the api-extended branch
