### ISSUE TITLE
Standardize API formula

### ISSUE THREAD

**Issue by schmelz21** [cisagov/pe-reports#57]
# 💡 Summary #

There is a large amount of data sources used to generate PE Reports +1.0.0. A standard code set is required to build continuity between developers for making request.

## Motivation and context ##

This issue is to review and discover best methods for the PE Team's API development.

## Implementation notes ##

Please review documents in the PE Teams File repository located:

_**Documents/Posture and Exposure/Temporary/Proposed API Standard/ Proposed API Standardization.docx**_

## Acceptance criteria ##

- [ ] PE Team Sign-off.

**Comment by schmelz21** [comment]
@DJensen94 , @elr64 , @stewartl97 , @aloftus23 , @cduhn17 feel free to pick away at this solution. Primary objective is us supplying code to the report builders in the same manor.

**Comment by cduhn17** [comment]
This implementation was very similar to the way I was interacting with the API.  Functionally this method produces the same output. I would not be opposed to using this method.

**Comment by schmelz21** [comment]
Question to the group - @cisagov/posture-and-exposure  
As we scale, is sourcing the data and calculating 'friendly-output' their own repos to be managed?
With a hierarchy:
- Report Generation and Delivery (pe-reports | pe-mailer)
- Metric Generation, Datastore and API (pe-metrics)
- Sourcing the Data (pe-sources) : 

> - src/credentials
> - src/masquerading
> - src/vulnerabilities
> - src/dark web
> - src/web defacement

**Comment by stewartl97** [comment]
Flask has been identified as the framework we will use.  There will be time set aside during Sprint 11 to address updating the documentation and data dictionaries to sync up the implementation of that framework.
