### ISSUE TITLE
Change Verbiage in PDF Report (Credential Publication and Abuse)

### ISSUE THREAD

**Issue by stewartl97** [cisagov/pe-reports#63]
# 🐛 Summary #
Verbiage used under section "Credential Publication and Abuse" on page 4 is incorrect.  

## Expected behavior ##

The verbiage needs to be change to the following:

"Exposed credentials put systems at risk for unauthorized access and users at risk for highly effective phishing attacks."

**Comment by stewartl97** [comment]
@DJensen94 This work was completed correct?

**Comment by DJensen94** [comment]
Wording has changed since this issues creation
