### ISSUE TITLE
POST Query score data

### ISSUE THREAD

**Issue by cduhn17** [cisagov/pe-reports#635]
# 💡 Summary #

Add new REST endpoints that mirror existing sql queries and replace existing sql query with REST
Specifically: Convert "query_score_data()" TSQL query to an API endpoint

## Motivation and context ##

There are two major reasons to use endpoints in place of sql queries.
- Replace the need to know t-sql
- Off load data aggregation to fastapi parallel workers

## Implementation notes ##

- Gather existing queries from code.
- Create new endpoints at fastapi.
- Secure new endpoints in same fashion as existing endpoint.

## Acceptance criteria ##

- [X] home/models.py model created
- [X] dataAPI/schemas.py schema created
- [X] dataAPI/views.py functions created
- [X] dataAPI/tasks.py function created
- [X] Create new endpoint /pescore_hist_domain_alert
- [X] Create new endpoint /pescore_hist_darkweb_alert 
- [X] Create new endpoint /pescore_hist_darkweb_ment
- [X] Create new endpoint /pescore_hist_cred
- [X] Create new endpoint /pescore_base_metrics
- [X] Verified endpoints are working
- [X] Code review and push changes

**Comment by arng4108** [comment]
Endpoint finished and pushed to the CD-pe-reports-api-extended branch
