### ISSUE TITLE
POST refresh mat_vw_breachcomp_breachdetails

### ISSUE THREAD

**Issue by edujosemena** [cisagov/pe-reports#668]
# 💡 Summary #

What is the work, as a high-level summary?

## Motivation and context ##
# 💡 Summary #
Add functionality to be able to refresh view and store on redis to be able to quickly query while running reports. Specifically for endpoint querying 'mat_vw_breachcomp_breachdetails'

## Motivation and context ##

There are two major reasons to use endpoints in place of sql queries.
- Replace the need to know t-sql
- Off load data aggregation to fastapi parallel workers

## Implementation notes ##

- Gather existing queries from code.
- Create task
- Cache Task ID for quick usage
- Create new endpoints at fastapi.
- Secure new endpoints in same fashion as existing endpoint.

## Acceptance criteria ##

- [ ] home/models.py model created
- [ ] dataAPI/schemas.py schema created 
- [ ] dataAPI/views.py functions created
- [ ] dataAPI/tasks.py function created
- [ ] Verified endpoint is working

**Comment by arng4108** [comment]
Refreshing this view has been consolidated under issue #617
