### ISSUE TITLE
P&E vs Tool Comparison Write-Up

### ISSUE THREAD

**Issue by arng4108** [cisagov/pe-reports#693]
# 💡 Summary #

We need to compare P&E's capabilities to a certain tool

## Motivation and context ##

We need to identify the differences and pros/cons between P&E and this tool

## Implementation notes ##

- Will involve researching this tool's capabilities
- Will involve reviewing P&E's capabilities
- A document covering all this information will need to be created
- This document could be used to compare P&E and the tool

## Acceptance criteria ##

- [X] Gain access to tool
- [x] Investigate tool's capabilities and check API availability
- [x] Create document with all this comparison information

**Comment by schmelz21** [comment]
Closed and Delivered 12/20/23
