### ISSUE TITLE
Update API-Extended Branch to Match Staging

### ISSUE THREAD

**Issue by arng4108** [cisagov/pe-reports#698]
# 💡 Summary #

Need to update the code in the CD-pe-reports-api-extended branch so that it has all the code necessary to function like staging. Currently, api-extended is missing quite a bit of code compared to staging

## Motivation and context ##

The api-extended branch will most likely be used for the new repository, so it needs to be brought up to date and be functional

## Implementation notes ##

- Need to ensure all code is present so that it can perform the same functions as staging
- Need to omit unnecessary, unused code
- Need to organize and label code while we're at it

## Acceptance criteria ##

- [X] API-related code has been brought up to date
- [X] Scan related code has been brought up to date
- [X] ASM sync related code has been brought up to date
- [X] PE report generation code has been brought up to date
- [X] PE report encryption code has been brought up to date
- [X] PE mailing code has been brought up to date
- [X] Database backup/restore code has been brought up to date
- [X] Scorecard module has been brought up to date
- [X] Lint and pre-commit checks

**Comment by schmelz21** [comment]
@arng4108 - per our sprint conversation. Can we mark this complete?

**Comment by arng4108** [comment]
@schmelz21 I'm still working on passing the pre-commit checks so I think this issue should stay open. Unless you think the pre-commit checks should be a separate issue?

**Comment by schmelz21** [comment]
Nope, lets keep it open.

**Comment by arng4108** [comment]
api-extended has been updated and is now waiting to be used for the new repo
