### ISSUE TITLE
Connect cyhy customer db to encrypt and embed pdf reports.

### ISSUE THREAD

**Issue by schmelz21** [cisagov/pe-reports#7]
# 💡 Summary #
Update the "report_generator.py" scripts to include a function "generate_reports" that coordinates the P&E Report process.

## Motivation and context ##
This is a key feature to securely deliver encrypted reports to Posture and Exposure customers.

## Implementation notes ##

Please provide details for implementation, such as:

- Create function "generate_reports" to include the following:
- Connect to the cyhy database. 
- Gathers customer information based on customer ID. 
- Builds the reports.
- Embed raw data into the pdf output. 
- Encrypts the pdfs.

## Acceptance criteria ##

How do we know when this work is done?

- [x] Produce P&E Report with no errors.
- [x] Output is encrypted.
- [x] Validate report data.
- [x] Review and ensure reports can be sent using current mailer scripts.

**Comment by stewartl97** [comment]
@elr64 can you verify and make sure that the next set of reports are sent using the mailer script?

**Comment by schmelz21** [comment]
@cduhn17 I switched assignments on this one as it will be included to the current PR we are trying to get merged. https://github.com/cisagov/pe-reports/pull/33

**Comment by cduhn17** [comment]
@schmelz-ctr , 

Is there any code started from elr64? That we are aware of, is there an encryption method "dev standard" that is recommended?

**Comment by schmelz21** [comment]
> @schmelz-ctr ,
> 
> Is there any code started from elr64? That we are aware of, is there an encryption method "dev standard" that is recommended?

@cduhn17 - It is already in the code leveraging the package `fitz` the following function in ss-working-test branch. 

[def embed_and_encrypt()](https://github.com/cisagov/pe-reports/blob/7115dd4ff176abfaf8144065cd03f5b35d74ff36/src/pe_reports/report_generator.py#L122)

There is no action on this, just tracking it at this point - gets introduced on that merge.
