### ISSUE TITLE
POST get_data_source_uid() Convert to API Endpoint

### ISSUE THREAD

**Issue by arng4108** [cisagov/pe-reports#700]
# 💡 Summary #

Replace the existing TSQL function with a new REST endpoint that does the same thing
Specifically: Convert "get_data_source_uid()" TSQL query to an API endpoint

## Motivation and context ##

There are two major reasons to use endpoints in place of sql queries.

- Replace the need to know t-sql
- Off load data aggregation to fastapi parallel workers

## Implementation notes ##

- Gather existing queries from code.
- Create new endpoints at fastapi.
- Secure new endpoints in same fashion as existing endpoint.

## Acceptance criteria ##

- [X] home/models.py model created
- [X] dataAPI/schemas.py schema created
- [X] dataAPI/views.py functions created
- [X] dataAPI/tasks.py function created (if applicable)
- [ ] Verified endpoint is working
- [ ] pushed to api extended/staging branch

**Comment by schmelz21** [comment]
Closing s all endpoint testing has moved to this https://github.com/cisagov/pe-reports/issues/705.
