### ISSUE TITLE
Create scripts to build charting metrics; credentials

### ISSUE THREAD

**Issue by schmelz21** [cisagov/pe-reports#78]
# 💡 Summary #

Create a a method to pull output data from `db_query.py` for charting. Create a function that manipulates the data to produce an organization's exposed credentials chart.

## Implementation notes ##

- create `pe_reports/metrics.py`
- create a function to handle an organization's exposed credentials
- Import `numpy` package
- Update `setup.py` with new libraries.

## Acceptance criteria ##

- [ ]  run `pip install -e .`
- [ ] run `pre-commit run --all-files`
- [ ] run `pytest /tests`
- [ ] run `pe-reports $(date "+%Y-%m-%d") data/ output/ --db-creds-file=/creds`
- [ ] All code meets dev-standards
- [ ] Changes are limited to a single goal - eschew scope creep!
- [ ] All future TODOs are captured in issues, which are referenced in code comments.
- [ ] All relevant type-of-change labels have been added.

**Comment by schmelz21** [comment]
@cisagov/posture-and-exposure - question / thoughts.
After reviewing the code on [report_metrics.py](https://github.com/cisagov/pe-reports/blob/AL-wip-v1.0-COOL/src/pe_reports/report_metrics.py), I would like to discuss converting over the metric _functions_ into _Class Instances_.

Classes could include our primary metric 'spaces': Credentials, Domain, Vulnerabilities, DarkWeb.
For example the Class `Credentials(self, start_date, end_date, org_uid)` could include:
- `creds_total`, returns `creds`
- `creds_password`, returns `pw_creds`
- `creds_breaches`, returns` breach`
- `creds_by_day`, returns `ce_date_df`
- `creads_breach_deails`, returns `breach_det_df` ...

The thought in doing so:
Consider our individual output (metrics) as bricks that build the house (reports). As we progress to grow out metrics/analytics we may want to access these metric points intermittently to generate new charts/graphs/data.

For example: Dark Web mentions "executive" and "credentials leak" info may be reported together.

**Comment by cduhn17** [comment]
I think it's a good idea. The time has come to implement more classes as things are getting more complex and code reuse being vital to maintain efficiency while scaling out our project.

**Comment by aloftus23** [comment]
Yes, agreed. The benefits make sense and don't see any reason not to.
