### ISSUE TITLE
Add "Mentions" processing scripts

### ISSUE THREAD

**Issue by schmelz21** [cisagov/pe-reports#81]
# 💡 Summary #

Create scripts to produce charting data that displays information about an organizations web and dark web mentions.

## Implementation notes ##

- Add in function `mention_metrics` to `db_query.py`
- Return dataframes

## Acceptance criteria ##

How do we know when this work is done?

- [ ]  run `pip install -e .`
- [ ] run `pre-commit run --all-files`
- [ ] run `pytest /tests`
- [ ] run `pe-reports $(date "+%Y-%m-%d") data/ output/ --db-creds-file=/creds`
- [ ] All code meets dev-standards
- [ ] Changes are limited to a single goal - eschew scope creep!
- [ ] All future TODOs are captured in issues, which are referenced in code comments.
- [ ] All relevant type-of-change labels have been added.

**Comment by stewartl97** [comment]
@DJensen94 Has this been merged into a PR?

**Comment by DJensen94** [comment]
Completed in PR #99
