### ISSUE TITLE
Add function to gather metrics for charts

### ISSUE THREAD

**Issue by schmelz21** [cisagov/pe-reports#82]
# 💡 Summary #

Create a function to gather all data from charting dataframes produced in `db_query.py`.

## Implementation notes ##

- Add in function `generate_metrics `to `db_query.py`
- Return dictionary

## Acceptance criteria ##

How do we know when this work is done?

- [ ] `run pip install -e .`
- [ ] `run pre-commit run --all-files`
- [ ] `run pytest /tests`
- [ ] `run pe-reports $(date "+%Y-%m-%d") data/ output/ --db-creds-file=/creds`
- [ ] All code meets dev-standards
- [ ] Changes are limited to a single goal - eschew scope creep!
- [ ] All future TODOs are captured in issues, which are referenced in code comments.
- [ ] All relevant type-of-change labels have been added.

**Comment by DJensen94** [comment]
We are no longer using a dictionary and instead implemented classes for each data source and it has been successfully implemented into the current report generator
