### ISSUE TITLE
Add "stacked_bar", "clustered_bar" and  "h_bar" Matplotlib charts

### ISSUE THREAD

**Issue by schmelz21** [cisagov/pe-reports#84]
# 💡 Summary #

Update the Class `Charts` with Matplotlib versions "stacked_bar", "clustered_bar" and  "h_bar".

## Implementation notes ##
- Create function `stacked_bar`
- Create function `clustered_bar`
- Create function `h_bar`

## Acceptance criteria ##

How do we know when this work is done?

- [ ]  run `pip install -e .`
- [ ] run `pre-commit run --all-files`
- [ ] run `pytest /tests`
- [ ] run `pe-reports $(date "+%Y-%m-%d") data/ output/ --db-creds-file=/creds`
- [ ] All code meets dev-standards
- [ ] Changes are limited to a single goal - eschew scope creep!
- [ ] All future TODOs are captured in issues, which are referenced in code comments.
- [ ] All relevant type-of-change labels have been added.

**Comment by DJensen94** [comment]
Implemented in the most recent version of the report
