### ISSUE TITLE
Add "line_chart", "line_chart2" and "pie" Matplotlib charts

### ISSUE THREAD

**Issue by schmelz21** [cisagov/pe-reports#85]
# 💡 Summary #

Update the Class Charts with Matplotlib versions "line_chart", "line_chart2" and "pie(chart)".

## Implementation notes ##

Please provide details for implementation, such as:

- Create function `line_chart`
- Create function `line_chart2` - lets look at a rename.
- Create function `pie(chart)`

## Acceptance criteria ##

How do we know when this work is done?

- [ ]  run `pip install -e .`
- [ ] run `pre-commit run --all-files`
- [ ] run `pytest /tests`
- [ ] run `pe-reports $(date "+%Y-%m-%d") data/ output/ --db-creds-file=/creds`
- [ ] All code meets dev-standards
- [ ] Changes are limited to a single goal - eschew scope creep!
- [ ] All future TODOs are captured in issues, which are referenced in code comments.
- [ ] All relevant type-of-change labels have been added.

**Comment by DJensen94** [comment]
successfully implemented into newest version of the report
