### ISSUE TITLE
Introduce Chevron framework

### ISSUE THREAD

**Issue by schmelz21** [cisagov/pe-reports#86]
# 💡 Summary #

Replace any `python-pptx` libraries with the `Chevron` libraries which includes html resources in the `pages.py` routine.

## Implementation notes ##
-  Delete `data/shell/pe_shell.pptx`
- Add `data/chevron/html01.html`
- Add `data/chevron/style.css`
- Add `credentials` chart generation

## Acceptance criteria ##

How do we know when this work is done?

- [ ] run `pip install -e .`
- [ ] run `pre-commit run --all-files`
- [ ] run `pytest /tests`
- [ ] run `pe-reports $(date "+%Y-%m-%d") data/ output/ --db-creds-file=/creds`
- [ ] All code meets dev-standards
- [ ] Changes are limited to a single goal - eschew scope creep!
- [ ] All future TODOs are captured in issues, which are referenced in code comments.
- [ ] All relevant type-of-change labels have been added.

**Comment by DJensen94** [comment]
Successfully past dev checks in PR #114
