### ISSUE TITLE
Add dark web functions to build pages

### ISSUE THREAD

**Issue by schmelz21** [cisagov/pe-reports#88]
# 💡 Summary #

Add function for generating dark web pages in `pages.py`.
## Acceptance criteria ##

How do we know when this work is done?

- [ ] run `pip install -e .`
- [ ] run `pre-commit run --all-files`
- [ ] run `pytest /tests`
- [ ] run `pe-reports $(date "+%Y-%m-%d") data/ output/ --db-creds-file=/creds`
- [ ] All code meets dev-standards
- [ ] Changes are limited to a single goal - eschew scope creep!
- [ ] All future TODOs are captured in issues, which are referenced in code comments.
- [ ] All relevant type-of-change labels have been added.

**Comment by DJensen94** [comment]
completed in current version of the scripts
