### ISSUE TITLE
Add table build function and appendix pages.

### ISSUE THREAD

**Issue by schmelz21** [cisagov/pe-reports#89]
# 💡 Summary #

Add` buildTable`, `buildAppendixList` and `init` to `pages.py` .

## Acceptance criteria ##
- [ ] run `pip install -e .`
- [ ] run `pre-commit run --all-files`
- [ ] run `pytest /tests`
- [ ] run `pe-reports $(date "+%Y-%m-%d") data/ output/ --db-creds-file=/creds`
- [ ] All code meets dev-standards
- [ ] Changes are limited to a single goal - eschew scope creep!
- [ ] All future TODOs are captured in issues, which are referenced in code comments.
- [ ] All relevant type-of-change labels have been added.

**Comment by DJensen94** [comment]
Has been implemented in the current version of the report
