### ISSUE TITLE
Define constants for graph sizing and positioning.

### ISSUE THREAD

**Issue by schmelz21** [cisagov/pe-reports#9]
# 💡 Summary #
In pages.py, remove hard-coded values addressing graph size positioning:
- x = width
- y = hight
- cx = graph position horizontal
- cy = graph position vertical

Example code:
```
 x, y, cx, cy = Inches(8.25), Inches(4.9), Inches(4.5), Inches(2.0)
 chart = slide.shapes.add_chart(
            XL_CHART_TYPE.COLUMN_STACKED_100, x, y, cx, cy, chart
            ).chart
            Graph.chart_sm(prs, slide, chart)
```

## Motivation and context ##

Additional value will be found on a complete P&E Reports build-out as each graphs size and positioning may constitute a method or "graph type" in stylesheets.py.

## Implementation notes ##

Issue noted - https://github.com/cisagov/pe-reports/pull/6#discussion_r657333800
Create constants for each graph type.

## Acceptance criteria ##

How do we know when this work is done?

- [ ] No hard-coded values will be found in the page generating functions.

**Comment by stewartl97** [comment]
@aloftus23  has this been completed?

**Comment by aloftus23** [comment]
Yes this can be closed. This refers to the old pe-reports version 0.1. And the code now follows these standards.
