### ISSUE TITLE
Create UI and method to manage accounts

### ISSUE THREAD

**Issue by stewartl97** [cisagov/pe-reports#98]
# 💡 Summary #

Create an interface that simplifies the work involved in setting up and managing new stakeholders.

## Motivation and context ##

This sprint is focused on adding new stakeholders, and as such we need to be able to add them in at each report period with minimal errors.

## Implementation notes ##

The management utility needs to be able to create new customers on the various service provider sites and update the PE database with any new entries.  The utility also needs to be able to modify existing records.

## Acceptance criteria ##

How do we know when this work is done?

- [x] CD - Include naming convention for orgs.
- [x] CD - Test theory Wrk Browser/ COOL / Bastian / Crossfeed Instance SQL
- [x] CD - Framework (pe-reports(flask)/pe-reports-docker) 
- [x] CD - define pieces for each org. (Add/Edit/Remove)
- [x] CD - CyberSix Integration
- [x] CD - Database Updates - Map out dependences for the org.
- [x] CD / GV - Capture Agency Executive list (Wikipedia)
- [x] GV - Test UI to db interactions

**Comment by DJensen94** [comment]
Addressed by PR #115, currently waiting for review
